name: deploy2github

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:

  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
     
      # ionic
      - name: Use coturiv/setup-ionic
        env:
          URL: ${{ secrets.URL }} 
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8
      - name: Build
        run: |
          ionic build --prod  -- --base-href ${{ secrets.URL }} 
          
      - name: Deploy  
         
        run: |
          npm install angular-cli-github-pages
          npx angular-cli-ghpages --dir=www



          


